### ISSUE TITLE
MT0013: Filtering out list of TMs that are not human aligned

### ISSUE THREAD

**Issue by gangagyatso4364** [OpenPecha/google_sheet_parser#1]
### Description 

Since we are realign all the repos that are not aligned by human with the new aligner algo , we need a list of repos or TMs that are machine aligned 

###  Completion criteria 

List of all the TMs that are not aligned by humans 

### Subtask

- [x] copy google sheet parser script
- [x] get credentials
- [x] select google sheet names to be parsed
- [x] create tm repo filtering script
- [x] test_case
